1. Import the NUMPY package under the name np.

In [3]:
import numpy as np

2. Print the NUMPY version and the configuration.

In [4]:
print(np.__version__)

1.26.1


3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"<br>
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
# 1. We with randit
a = np.random.randint(100,size=(2,3,5))
print(a)
print(type(a))


[[[11 17 14 37 65]
  [44 67 52 45 52]
  [86 47 91  1 49]]

 [[69 99 54 97 90]
  [90 19 33 70 26]
  [92 80 11 94 24]]]
<class 'numpy.ndarray'>


4. Print a.

In [6]:
print(a)

[[[11 17 14 37 65]
  [44 67 52 45 52]
  [86 47 91  1 49]]

 [[69 99 54 97 90]
  [90 19 33 70 26]
  [92 80 11 94 24]]]


5. Create a 5x2x3 3-dimensional array with all values equaling 1.<br>
ssign the array to variable "b"

In [7]:
b = np.ones((5,2,3), dtype= int)

6. Print b.

In [8]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


7. Do a and b have the same size? How do you prove that in Python code?

Yes they have the same size

In [9]:
print(np.size(a), np.size(b))

30 30


8. Are you able to add a and b? Why or why not?

We can't because they different dimension

In [10]:
print(a.shape, b.shape)

(2, 3, 5) (5, 2, 3)


In [11]:
try:
    sum(a,b)
except:
    print("The 2 arrays have diffent shape")

The 2 arrays have diffent shape


9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [12]:
c = b.transpose(1,2,0)
print(c.shape)
print(c)

(2, 3, 5)
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [13]:
d = c + a

11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [14]:

print(d)


[[[ 12  18  15  38  66]
  [ 45  68  53  46  53]
  [ 87  48  92   2  50]]

 [[ 70 100  55  98  91]
  [ 91  20  34  71  27]
  [ 93  81  12  95  25]]]


12. Multiply a and c. Assign the result to e.

In [15]:
e = a * c
e

array([[[11, 17, 14, 37, 65],
        [44, 67, 52, 45, 52],
        [86, 47, 91,  1, 49]],

       [[69, 99, 54, 97, 90],
        [90, 19, 33, 70, 26],
        [92, 80, 11, 94, 24]]])

13. Does e equal to a? Why or why not?

The result is equal to A because we're doing the procut with an Array compose of ones. We are able to do the product of both ARRAYS because they have the same shape.

14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [16]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max, d_min,d_mean)

100 2 55.2


15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [33]:
f = np.empty((2,3,5))


16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.<br>
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.<br>
If a value equals to d_mean, assign 50 to the corresponding value in f.<br>
Assign 0 to the corresponding value(s) in f for d_min in d.<br>
Assign 100 to the corresponding value(s) in f for d_max in d.<br>
In the end, f should have only the following values: 0, 25, 50, 75, and 100.<br>
Note: you don't have to use Numpy in this question.<br>


In [34]:
for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 25
            if d[i][j][k] > d_mean:
                f[i][j][k] = 5
            if d[i][j][k] == d_mean:
                f[i][j][k] = 50 
            if d[i][j][k] == d_min:
                f[i][j][k] = 0                 
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100


In [35]:
print(f)

TypeError: 'numpy.ndarray' object is not callable

17. Print d and f. Do you have your expected f?<br>
For instance, if your d is:<br>
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],<br>
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],<br>
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],<br>
       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],<br>
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],<br>
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])<br>
Your f should be:<br>
array([[[ 75.,  75.,  75.,  25.,  75.],<br>
        [ 75.,  75.,  25.,  25.,  25.],<br>
        [ 75.,  25.,  75.,  75.,  75.]],<br>
       [[ 25.,  25.,  25.,  25., 100.],<br>
        [ 75.,  75.,  75.,  75.,  75.],<br>
        [ 25.,  75.,   0.,  75.,  75.]]])<br>



<br>
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values <br>
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:<br>
array([[[ 'D',  'D',  'D',  'B',  'D'],<br>
        [ 'D',  'D',  'B',  'B',  'B'],<br>
        [ 'D',  'B',  'D',  'D',  'D']],<br>
       [[ 'B',  'B',  'B',  'B',  'E'],<br>
        [ 'D',  'D',  'D',  'D',  'D'],<br>
        [ 'B',  'D',   'A',  'D', 'D']]])<br>
Again, you don't need Numpy in this question.<br>
