In [906]:
# 1. Import the NUMPY package under the name np.
import numpy as np

In [907]:
# 2. Print the NUMPY version and the configuration.
print("version:", np.version.version)
print("--")
np. show_config()


version: 1.24.1
--
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_

In [908]:
# 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random((2, 3, 5))

In [909]:
# 4. Print a.
a

array([[[0.57485532, 0.88090983, 0.55910758, 0.42921281, 0.3631501 ],
        [0.6674474 , 0.65087378, 0.24494241, 0.41568877, 0.5675643 ],
        [0.5197136 , 0.43954487, 0.77769719, 0.31542534, 0.36488613]],

       [[0.04350651, 0.32742911, 0.04886006, 0.75453739, 0.74074782],
        [0.09702833, 0.90102115, 0.43271407, 0.51671031, 0.23660598],
        [0.95918773, 0.36345007, 0.20740672, 0.93400986, 0.43963275]]])

In [910]:
# 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones(((5, 2, 3)), dtype=int)

In [911]:
# 6. Print b.
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [912]:
# 7. Do a and b have the same size? How do you prove that in Python code?
a.size == b.size

True

In [913]:
# 8. Are you able to add a and b? Why or why not?
try:
    a + b
except ValueError:
    print("You can't because although having the same sizes, the shapes of each array are not the same.")

You can't because although having the same sizes, the shapes of each array are not the same.


In [914]:
# 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
print(a.shape)
print(b.shape)

c = b.transpose(1, 2, 0)

(2, 3, 5)
(5, 2, 3)


In [915]:
# 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
# Now it can't be printed because the shapes of both array are the same and therefore it can be done.
d = a + c
d

array([[[1.57485532, 1.88090983, 1.55910758, 1.42921281, 1.3631501 ],
        [1.6674474 , 1.65087378, 1.24494241, 1.41568877, 1.5675643 ],
        [1.5197136 , 1.43954487, 1.77769719, 1.31542534, 1.36488613]],

       [[1.04350651, 1.32742911, 1.04886006, 1.75453739, 1.74074782],
        [1.09702833, 1.90102115, 1.43271407, 1.51671031, 1.23660598],
        [1.95918773, 1.36345007, 1.20740672, 1.93400986, 1.43963275]]])

In [916]:
# 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
# Array d's values are array a's values plus 1, which are the values from the b/c array that we were working on before.
print(a)
print("--")
print(d)

[[[0.57485532 0.88090983 0.55910758 0.42921281 0.3631501 ]
  [0.6674474  0.65087378 0.24494241 0.41568877 0.5675643 ]
  [0.5197136  0.43954487 0.77769719 0.31542534 0.36488613]]

 [[0.04350651 0.32742911 0.04886006 0.75453739 0.74074782]
  [0.09702833 0.90102115 0.43271407 0.51671031 0.23660598]
  [0.95918773 0.36345007 0.20740672 0.93400986 0.43963275]]]
--
[[[1.57485532 1.88090983 1.55910758 1.42921281 1.3631501 ]
  [1.6674474  1.65087378 1.24494241 1.41568877 1.5675643 ]
  [1.5197136  1.43954487 1.77769719 1.31542534 1.36488613]]

 [[1.04350651 1.32742911 1.04886006 1.75453739 1.74074782]
  [1.09702833 1.90102115 1.43271407 1.51671031 1.23660598]
  [1.95918773 1.36345007 1.20740672 1.93400986 1.43963275]]]


In [917]:
# 12. Multiply a and c. Assign the result to e.
e = a * c

In [918]:
# 13. Does e equal to a? Why or why not?
# e does equal a because we just multiplied all values of array a by 1 (all values of array c).

In [919]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean".
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)

In [920]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty((2,3,5))
f

array([[[0.5271177 , 0.95455118, 0.20294793, 0.40347215, 0.08269049],
        [0.10321868, 0.005264  , 0.19727896, 0.45559368, 0.81141968],
        [0.33009072, 0.99484183, 0.0238141 , 0.79810465, 0.16384766]],

       [[0.8117101 , 0.11536968, 0.86147976, 0.73294066, 0.80734859],
        [0.99662125, 0.83537524, 0.35172852, 0.41894545, 0.23487772],
        [0.72032889, 0.58746752, 0.08823937, 0.98245729, 0.18600065]]])

In [921]:
"""
16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 75
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50
            elif d[i][j][k] == d_min:
                f[i][j][k] = 0
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100

In [922]:
"""
# 17. Print d and f.
"""

print(d)
print("--")
print(f)

[[[1.57485532 1.88090983 1.55910758 1.42921281 1.3631501 ]
  [1.6674474  1.65087378 1.24494241 1.41568877 1.5675643 ]
  [1.5197136  1.43954487 1.77769719 1.31542534 1.36488613]]

 [[1.04350651 1.32742911 1.04886006 1.75453739 1.74074782]
  [1.09702833 1.90102115 1.43271407 1.51671031 1.23660598]
  [1.95918773 1.36345007 1.20740672 1.93400986 1.43963275]]]
--
[[[ 75.  75.  75.  25.  25.]
  [ 75.  75.  25.  25.  75.]
  [ 75.  25.  75.  25.  25.]]

 [[  0.  25.  25.  75.  75.]
  [ 25.  75.  25.  75.  25.]
  [100.  25.  25.  75.  25.]]]


In [924]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements?
"""

x = [[[0, 0, 0, 0, 0],[0, 0, 0, 0, 0],[0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]]
y = np.zeros((2,3,5))

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                x[i][j][k] = "B"
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                x[i][j][k] = "D"
            elif d[i][j][k] == d_mean:
                x[i][j][k] = "C"
            elif d[i][j][k] == d_min:
                x[i][j][k] = "A"
            elif d[i][j][k] == d_max:
                x[i][j][k] = "E"