In [2]:
#1. Import the NUMPY package under the name np.

import numpy as np

In [3]:
#2. Print the NUMPY version and the configuration.

print(np.version.version)

1.26.0


In [8]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random((2,3,5))


In [9]:
#4. Print a.
a

array([[[0.7526861 , 0.88161134, 0.040113  , 0.9682027 , 0.22825111],
        [0.60061964, 0.09773518, 0.34704848, 0.13854004, 0.9781127 ],
        [0.59388505, 0.05230312, 0.07939614, 0.50513025, 0.30175203]],

       [[0.5566256 , 0.9956584 , 0.61252727, 0.85991003, 0.30842392],
        [0.36075712, 0.23135583, 0.52093942, 0.3223463 , 0.12806055],
        [0.70516468, 0.44155237, 0.55611476, 0.65653224, 0.82274355]]])

In [10]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5, 2, 3))

In [11]:
#6. Print b.
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [17]:
#7. Do a and b have the same size? How do you prove that in Python code?
a.size == b.size

True

In [35]:
#8. Are you able to add a and b? Why or why not?     ValueError

try:
    a + b
except ValueError:
    print("operands could not be broadcast together with shapes (2,3,5) (5,2,3)")



operands could not be broadcast together with shapes (2,3,5) (5,2,3)


In [39]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


c = b.transpose(1, 2, 0)

c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [51]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = a + c

#its is now posiible because they now have the same shape

In [52]:

#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print(a)

print(d)

#d is just equal to a + d as every value in a has been added by 1

[[[0.7526861  0.88161134 0.040113   0.9682027  0.22825111]
  [0.60061964 0.09773518 0.34704848 0.13854004 0.9781127 ]
  [0.59388505 0.05230312 0.07939614 0.50513025 0.30175203]]

 [[0.5566256  0.9956584  0.61252727 0.85991003 0.30842392]
  [0.36075712 0.23135583 0.52093942 0.3223463  0.12806055]
  [0.70516468 0.44155237 0.55611476 0.65653224 0.82274355]]]
[[[1.7526861  1.88161134 1.040113   1.9682027  1.22825111]
  [1.60061964 1.09773518 1.34704848 1.13854004 1.9781127 ]
  [1.59388505 1.05230312 1.07939614 1.50513025 1.30175203]]

 [[1.5566256  1.9956584  1.61252727 1.85991003 1.30842392]
  [1.36075712 1.23135583 1.52093942 1.3223463  1.12806055]
  [1.70516468 1.44155237 1.55611476 1.65653224 1.82274355]]]


In [47]:
#12. Multiply a and c. Assign the result to e.

e = a * c



array([[[0.7526861 , 0.88161134, 0.040113  , 0.9682027 , 0.22825111],
        [0.60061964, 0.09773518, 0.34704848, 0.13854004, 0.9781127 ],
        [0.59388505, 0.05230312, 0.07939614, 0.50513025, 0.30175203]],

       [[0.5566256 , 0.9956584 , 0.61252727, 0.85991003, 0.30842392],
        [0.36075712, 0.23135583, 0.52093942, 0.3223463 , 0.12806055],
        [0.70516468, 0.44155237, 0.55611476, 0.65653224, 0.82274355]]])

In [48]:
#13. Does e equal to a? Why or why not?
e == a

#yes they are equal because 'e' is 'a' multiplied by one

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [57]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max = np.max(d)

d_min = np.min(d)

d_mean = np.mean(d)

print("The max value of d is", d_max)
print("The min value of d is", d_min)
print("The mean value of d is", d_mean)


The max value of d is 1.9956584011061855
The min value of d is 1.0401129984264466
The mean value of d is 1.4881366300353638


In [59]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty((2, 3, 5))

#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

In [62]:
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d_min < d[i][j][k] and d_mean> d[i][j][k]:
                f[i][j][k] = 25
            elif d_mean < d[i][j][k] and d_max > d[i][j][k]:
                f[i][j][k] = 75
            elif d_mean == d[i][j][k]:
                f[i][j][k] = 50
            elif d_min == d[i][j][k]:
                f[i][j][k] = 0
            elif d_max == d[i][j][k]:
                f[i][j][k] = 100


#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

In [64]:
print(d)

print(f)

#yes f is as expecteed as the value have changed correctly

[[[1.7526861  1.88161134 1.040113   1.9682027  1.22825111]
  [1.60061964 1.09773518 1.34704848 1.13854004 1.9781127 ]
  [1.59388505 1.05230312 1.07939614 1.50513025 1.30175203]]

 [[1.5566256  1.9956584  1.61252727 1.85991003 1.30842392]
  [1.36075712 1.23135583 1.52093942 1.3223463  1.12806055]
  [1.70516468 1.44155237 1.55611476 1.65653224 1.82274355]]]
[[[ 75.  75.   0.  75.  25.]
  [ 75.  25.  25.  25.  75.]
  [ 75.  25.  25.  75.  25.]]

 [[ 75. 100.  75.  75.  25.]
  [ 25.  25.  75.  25.  25.]
  [ 75.  25.  75.  75.  75.]]]
