1. Import the NUMPY package under the name np.

In [2]:
!pip install numpy
import numpy as np

2. Print the NUMPY version and the configuration.

In [3]:
print("numpy version: ", np.__version__)
print("numpy configuration: ")
np.show_config()

numpy version:  1.26.1
numpy configuration: 
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=3
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4378818576
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.1
Compilers:
  c:
    commands: clang
    linker: ld64
    name: clang
    version: 14.0.0
  c++:
    commands: clang++
    linker: ld64
    name: clang
    version: 14.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.3
Machine Information:
  build:
    cpu: x86_64
    endian: littl

3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"<br>
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:
# first way
a = np.random.randint(101, size = (2, 3, 5))

4. Print a.

In [9]:
print(a)

[[[ 89  46  27  58  29]
  [ 41  14  95   0  67]
  [ 82  13  46  44  23]]

 [[ 47  25  29  28 100]
  [ 67  94  82  26  82]
  [ 32  48  46  25  18]]]


5. Create a 5x2x3 3-dimensional array with all values equaling 1.<br>
ssign the array to variable "b"

In [46]:
b = np.random.randint(1, 2, size = (5, 2, 3))

6. Print b.

In [47]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


7. Do a and b have the same size? How do you prove that in Python code?

In [48]:
# option 1

print(a.size)
print(b.size)

30
30


In [49]:
# option 2

a.size == b.size

True

8. Are you able to add a and b? Why or why not?

No, because they don't have the same shape.

9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [50]:
# I look at a, and put the positions of b.

c = b.transpose(1, 2, 0)
print(c)
print(a)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
[[[ 89  46  27  58  29]
  [ 41  14  95   0  67]
  [ 82  13  46  44  23]]

 [[ 47  25  29  28 100]
  [ 67  94  82  26  82]
  [ 32  48  46  25  18]]]


10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [51]:
d = a + c
print(d)

[[[ 90  47  28  59  30]
  [ 42  15  96   1  68]
  [ 83  14  47  45  24]]

 [[ 48  26  30  29 101]
  [ 68  95  83  27  83]
  [ 33  49  47  26  19]]]


11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [52]:
print(a)

[[[ 89  46  27  58  29]
  [ 41  14  95   0  67]
  [ 82  13  46  44  23]]

 [[ 47  25  29  28 100]
  [ 67  94  82  26  82]
  [ 32  48  46  25  18]]]


In [53]:
print(d)

[[[ 90  47  28  59  30]
  [ 42  15  96   1  68]
  [ 83  14  47  45  24]]

 [[ 48  26  30  29 101]
  [ 68  95  83  27  83]
  [ 33  49  47  26  19]]]


12. Multiply a and c. Assign the result to e.

In [54]:
print(a)

[[[ 89  46  27  58  29]
  [ 41  14  95   0  67]
  [ 82  13  46  44  23]]

 [[ 47  25  29  28 100]
  [ 67  94  82  26  82]
  [ 32  48  46  25  18]]]


In [55]:
e = a * c
print(e)

[[[ 89  46  27  58  29]
  [ 41  14  95   0  67]
  [ 82  13  46  44  23]]

 [[ 47  25  29  28 100]
  [ 67  94  82  26  82]
  [ 32  48  46  25  18]]]


13. Does e equal to a? Why or why not?

Yes, because al the elements of c are 1. 

14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [57]:
d_max = d.max()
print(d_max)

101


In [59]:
d_min = d.min()
print(d_min)

1


In [60]:
d_mean = d.mean()
print(d_mean)

48.43333333333333


15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [81]:
f = np.empty((2, 3, 5), dtype="int")

16.
<br>
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.<br>
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.<br>
If a value equals to d_mean, assign 50 to the corresponding value in f.<br>
Assign 0 to the corresponding value(s) in f for d_min in d.<br>
Assign 100 to the corresponding value(s) in f for d_max in d.<br>
In the end, f should have only the following values: 0, 25, 50, 75, and 100.<br>
Note: you don't have to use Numpy in this question.<br>


In [82]:
# solution to question 16
#option 1

for i in range(d.shape[0]):
    for x in range(d.shape[1]):
        for z in range(d.shape[2]):
            val = d[i][x][z]
            if val > d_min and val < d_mean:
                f[i][x][z] = 25
            elif val > d_mean and val < d_max:
                f[i][x][z] = 75
            elif val == d_mean:
                f[i][x][z] = 50
            elif val == d_min:
                f[i][x][z] = 0
            elif val == d_max:
                f[i][x][z] = 100

In [83]:
print(f)

[[[ 75  25  25  75  25]
  [ 25  25  75   0  75]
  [ 75  25  25  25  25]]

 [[ 25  25  25  25 100]
  [ 75  75  75  25  75]
  [ 25  75  25  25  25]]]


In [84]:
# solution to question 16
#option 2

for i in range(2):
    for x in range(3):
        for z in range(5):
            val = d[i][x][z]
            if val > d_min and val < d_mean:
                f[i][x][z] = 25
            elif val > d_mean and val < d_max:
                f[i][x][z] = 75
            elif val == d_mean:
                f[i][x][z] = 50
            elif val == d_min:
                f[i][x][z] = 0
            elif val == d_max:
                f[i][x][z] = 100

17.
<br>
#17. Print d and f. Do you have your expected f?<br>
For instance, if your d is:<br>
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],<br>
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],<br>
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],<br>
       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],<br>
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],<br>
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])<br>
Your f should be:<br>
array([[[ 75.,  75.,  75.,  25.,  75.],<br>
        [ 75.,  75.,  25.,  25.,  25.],<br>
        [ 75.,  25.,  75.,  75.,  75.]],<br>
       [[ 25.,  25.,  25.,  25., 100.],<br>
        [ 75.,  75.,  75.,  75.,  75.],<br>
        [ 25.,  75.,   0.,  75.,  75.]]])<br>


In [86]:
print(d)

[[[ 90  47  28  59  30]
  [ 42  15  96   1  68]
  [ 83  14  47  45  24]]

 [[ 48  26  30  29 101]
  [ 68  95  83  27  83]
  [ 33  49  47  26  19]]]


In [85]:
print(f)

[[[ 75  25  25  75  25]
  [ 25  25  75   0  75]
  [ 75  25  25  25  25]]

 [[ 25  25  25  25 100]
  [ 75  75  75  25  75]
  [ 25  75  25  25  25]]]


18.
<br>
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values <br>
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:<br>
array([[[ 'D',  'D',  'D',  'B',  'D'],<br>
        [ 'D',  'D',  'B',  'B',  'B'],<br>
        [ 'D',  'B',  'D',  'D',  'D']],<br>
       [[ 'B',  'B',  'B',  'B',  'E'],<br>
        [ 'D',  'D',  'D',  'D',  'D'],<br>
        [ 'B',  'D',   'A',  'D', 'D']]])<br>
Again, you don't need Numpy in this question.<br>


In [97]:
e = np.empty((2, 3, 5), dtype=str)

In [99]:
em_dict = {0:"A", 25:"B", 50:"C", 75:"D", 100:"E"}

In [100]:
for i in range(e.shape[0]):
    for x in range(e.shape[1]):
        for z in range(e.shape[2]):
            val = d[i][x][z]
            if val > d_min and val < d_mean:
                e[i][x][z] = em_dict[25]
            elif val > d_mean and val < d_max:
                e[i][x][z] = em_dict[75]
            elif val == d_mean:
                e[i][x][z] = em_dict[50]
            elif val == d_min:
                e[i][x][z] = em_dict[0]
            elif val == d_max:
                e[i][x][z] = em_dict[100]         

In [101]:
print(e)

[[['D' 'B' 'B' 'D' 'B']
  ['B' 'B' 'D' 'A' 'D']
  ['D' 'B' 'B' 'B' 'B']]

 [['B' 'B' 'B' 'B' 'E']
  ['D' 'D' 'D' 'B' 'D']
  ['B' 'D' 'B' 'B' 'B']]]
