. Import the NUMPY package under the name np.

In [103]:
import numpy as np
import random

. Print the NUMPY version and the configuration.

In [104]:
print(np.__version__)

1.26.0


. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"<br>
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [105]:
a = np.random.randint(101, size =(2, 3, 5))


. Print a.

In [106]:
a

array([[[ 71,  86,  82,  86,  88],
        [ 31,   9,  77,  68,  87],
        [  7,  51,  79,  37,  43]],

       [[ 21,  34,  19,  12,  20],
        [ 99,  84,  82,  22,  43],
        [100,  26, 100,  15,  25]]])

. Create a 5x2x3 3-dimensional array with all values equaling 1.<br>
ssign the array to variable "b"

In [107]:
b = np.ones((5, 2, 3))

. Print b.

In [108]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


. Do a and b have the same size? How do you prove that in Python code?

In [109]:
a.size == b.size

True

. Are you able to add a and b? Why or why not?

In [110]:
try:
    print(a + b)
except ValueError:
    print("You can't, because the shape is not the same which makes them not homogeneous and not summable")
    



You can't, because the shape is not the same which makes them not homogeneous and not summable


. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [111]:
c = b.transpose(1, 2, 0)

0. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [112]:
d = a + c
print("It works now because the Arrays are homogeneous")
d

It works now because the Arrays are homogeneous


array([[[ 72.,  87.,  83.,  87.,  89.],
        [ 32.,  10.,  78.,  69.,  88.],
        [  8.,  52.,  80.,  38.,  44.]],

       [[ 22.,  35.,  20.,  13.,  21.],
        [100.,  85.,  83.,  23.,  44.],
        [101.,  27., 101.,  16.,  26.]]])

1. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [113]:
print("Array A\n", a,"\n","Array D \n", d)
print("Each value of the array was summed by 1, as the other array had only ones as a number saved")

Array A
 [[[ 71  86  82  86  88]
  [ 31   9  77  68  87]
  [  7  51  79  37  43]]

 [[ 21  34  19  12  20]
  [ 99  84  82  22  43]
  [100  26 100  15  25]]] 
 Array D 
 [[[ 72.  87.  83.  87.  89.]
  [ 32.  10.  78.  69.  88.]
  [  8.  52.  80.  38.  44.]]

 [[ 22.  35.  20.  13.  21.]
  [100.  85.  83.  23.  44.]
  [101.  27. 101.  16.  26.]]]
Each value of the array was summed by 1, as the other array had only ones as a number saved


2. Multiply a and c. Assign the result to e.

In [114]:
e = a * c

3. Does e equal to a? Why or why not?

In [115]:
e == a
print("Because any number multiplied by the 'one array' will equal to itself as you are multiplying by one.")

Because any number multiplied by the 'one array' will equal to itself as you are multiplying by one.


4. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [116]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

5. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [117]:
f = np.empty((2, 3, 5))
f

array([[[  5.,  92.,  29.,  61.,  51.],
        [ 12.,  55.,   7.,   4.,  48.],
        [ 10., 100.,  42.,  24.,  76.]],

       [[ 27.,  19.,  87.,  33.,  72.],
        [ 20.,  42.,  13.,  38.,  31.],
        [ 65.,  75.,  57.,  49.,  68.]]])


<br>
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.<br>
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.<br>
If a value equals to d_mean, assign 50 to the corresponding value in f.<br>
Assign 0 to the corresponding value(s) in f for d_min in d.<br>
Assign 100 to the corresponding value(s) in f for d_max in d.<br>
In the end, f should have only the following values: 0, 25, 50, 75, and 100.<br>
Note: you don't have to use Numpy in this question.<br>


In [118]:
# f is an empty Array
for i in range(2):
    for x in range(3):
        for z in range(5):
            val = d[i][x][z]
            
            if val > d_min and val < d_mean:
                f[i][x][z] = 25
            elif val > d_mean and val < d_max:
                f[i][x][z] = 75
            elif val == d_mean:
                f[i][x][z] = 50
            elif val == d_min:
                f[i][x][z] = 0
            elif val == d_max:
                f[i][x][z] = 100
print(f)


[[[ 75.  75.  75.  75.  75.]
  [ 25.  25.  75.  75.  75.]
  [  0.  25.  75.  25.  25.]]

 [[ 25.  25.  25.  25.  25.]
  [ 75.  75.  75.  25.  25.]
  [100.  25. 100.  25.  25.]]]



<br>
#17. Print d and f. Do you have your expected f?<br>
For instance, if your d is:<br>
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],<br>
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],<br>
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],<br>
       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],<br>
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],<br>
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])<br>
Your f should be:<br>
array([[[ 75.,  75.,  75.,  25.,  75.],<br>
        [ 75.,  75.,  25.,  25.,  25.],<br>
        [ 75.,  25.,  75.,  75.,  75.]],<br>
       [[ 25.,  25.,  25.,  25., 100.],<br>
        [ 75.,  75.,  75.,  75.,  75.],<br>
        [ 25.,  75.,   0.,  75.,  75.]]])<br>



<br>
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values <br>
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:<br>
array([[[ 'D',  'D',  'D',  'B',  'D'],<br>
        [ 'D',  'D',  'B',  'B',  'B'],<br>
        [ 'D',  'B',  'D',  'D',  'D']],<br>
       [[ 'B',  'B',  'B',  'B',  'E'],<br>
        [ 'D',  'D',  'D',  'D',  'D'],<br>
        [ 'B',  'D',   'A',  'D', 'D']]])<br>
Again, you don't need Numpy in this question.<br>
