. Import the NUMPY package under the name np.

In [15]:
import numpy as np
import random

In [16]:
def numpy_info (array):
    print(f"The type is {type(array)}")
    print(f"The n.dim is {array.ndim}")
    print(f"The shape is {array.shape}")
    print(f"The size is {array.size}")

. Print the NUMPY version and the configuration.

In [17]:
print(np.__version__)
print(np.show_config)

1.26.1
<function show at 0x104c34fe0>


. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"<br>
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [18]:
a = np.random.randint(100, size = (2, 3, 5))
numpy_info(a)
a_1 = np.random.rand(2, 3, 5)
numpy_info(a_1)
a_2 = np.random.choice(100, size= (2, 3, 5))
numpy_info(a_2)

The type is <class 'numpy.ndarray'>
The n.dim is 3
The shape is (2, 3, 5)
The size is 30
The type is <class 'numpy.ndarray'>
The n.dim is 3
The shape is (2, 3, 5)
The size is 30
The type is <class 'numpy.ndarray'>
The n.dim is 3
The shape is (2, 3, 5)
The size is 30


. Print a.

In [19]:
print(a_1)
print(a_2)
print(a_2)

[[[0.19054229 0.08811853 0.9689958  0.45814016 0.83376166]
  [0.39145568 0.81129293 0.00854977 0.646514   0.63518629]
  [0.53433367 0.6294305  0.13253987 0.07989989 0.05865877]]

 [[0.5533395  0.72889715 0.09546565 0.60474081 0.34365328]
  [0.00190017 0.40331366 0.41965764 0.64858559 0.44769148]
  [0.27414328 0.11926717 0.98149418 0.08919737 0.60571278]]]
[[[ 9 87 83 98 83]
  [35 28 28 34 81]
  [69 19 42 99 57]]

 [[93 81 36 26 52]
  [68  0 35 84  2]
  [34 30 78 94 76]]]
[[[ 9 87 83 98 83]
  [35 28 28 34 81]
  [69 19 42 99 57]]

 [[93 81 36 26 52]
  [68  0 35 84  2]
  [34 30 78 94 76]]]


. Create a 5x2x3 3-dimensional array with all values equaling 1.<br>
ssign the array to variable "b"

In [20]:
b = np.ones((5, 2, 3))
numpy_info(b)

The type is <class 'numpy.ndarray'>
The n.dim is 3
The shape is (5, 2, 3)
The size is 30


. Print b.

In [21]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


. Do a and b have the same size? How do you prove that in Python code?

In [22]:
a.size == b.size
print(a.size)
print(b.size)

30
30


. Are you able to add a and b? Why or why not?<br>
a + b  -> ValueError<br>
e cannot add a + b because even though the size is the same, the shape is not so in order to be able to aperate between those arrays, we'd need to transpose.

. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [23]:
print(a.shape)
print(b.shape)

(2, 3, 5)
(5, 2, 3)


In [24]:
c = b.transpose(1, 2, 0)
print(c.shape)

(2, 3, 5)


0. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [25]:
d = a + c
print(d)

[[[96. 86. 50. 71. 44.]
  [68. 78. 23. 60. 61.]
  [43. 91. 22. 70. 80.]]

 [[98. 37. 18.  3. 22.]
  [75. 97. 84. 35. 32.]
  [96. 18. 74. 66. 69.]]]


1. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [26]:
print(a)
print(d)
'''as c was a ones array, when we changed the shape, we could superpose the both of them and do the addition.
This is why the values are the innitial ones +1. 
But we can also observe that the d array has a dot after each value, I think that happens because normally
an array of ones as an array of 0 are used to create masks aka a filter to an array with a condition to return True or false
and only show the True ones, that is when the condition is met'''

[[[95 85 49 70 43]
  [67 77 22 59 60]
  [42 90 21 69 79]]

 [[97 36 17  2 21]
  [74 96 83 34 31]
  [95 17 73 65 68]]]
[[[96. 86. 50. 71. 44.]
  [68. 78. 23. 60. 61.]
  [43. 91. 22. 70. 80.]]

 [[98. 37. 18.  3. 22.]
  [75. 97. 84. 35. 32.]
  [96. 18. 74. 66. 69.]]]


'as c was a ones array, when we changed the shape, we could superpose the both of them and do the addition.\nThis is why the values are the innitial ones +1. \nBut we can also observe that the d array has a dot after each value, I think that happens because normally\nan array of ones as an array of 0 are used to create masks aka a filter to an array with a condition to return True or false\nand only show the True ones, that is when the condition is met'

2. Multiply a and c. Assign the result to e.

In [27]:
e = a * c
print(e)
print(a)
numpy_info(e)
numpy_info(a)

[[[95. 85. 49. 70. 43.]
  [67. 77. 22. 59. 60.]
  [42. 90. 21. 69. 79.]]

 [[97. 36. 17.  2. 21.]
  [74. 96. 83. 34. 31.]
  [95. 17. 73. 65. 68.]]]
[[[95 85 49 70 43]
  [67 77 22 59 60]
  [42 90 21 69 79]]

 [[97 36 17  2 21]
  [74 96 83 34 31]
  [95 17 73 65 68]]]
The type is <class 'numpy.ndarray'>
The n.dim is 3
The shape is (2, 3, 5)
The size is 30
The type is <class 'numpy.ndarray'>
The n.dim is 3
The shape is (2, 3, 5)
The size is 30


3. Does e equal to a? Why or why not?

In [28]:
a == e 

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])


 Yes, because it e equals a, the first array multiplied with c, the ones mask, so basically you are passing a mask of always true.<br>
so c is a ones array, so it multiplies per one. I don't know if that means that e becomes a mask, because of the dots?


4. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [29]:
d_max = np.max(d)
print(d_max)

98.0


In [30]:
d_min= np.min(d)
print(d_min)

3.0


In [31]:
d_mean = np.mean(d)
print(d_mean)

58.9


5. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [32]:
f = np.empty((2, 3, 5))
print(f)
numpy_info(f)

[[[95. 85. 49. 70. 43.]
  [67. 77. 22. 59. 60.]
  [42. 90. 21. 69. 79.]]

 [[97. 36. 17.  2. 21.]
  [74. 96. 83. 34. 31.]
  [95. 17. 73. 65. 68.]]]
The type is <class 'numpy.ndarray'>
The n.dim is 3
The shape is (2, 3, 5)
The size is 30


he result say that f == e and f == d

In [33]:
f == e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])


<br>
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.<br>
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.<br>
If a value equals to d_mean, assign 50 to the corresponding value in f.<br>
Assign 0 to the corresponding value(s) in f for d_min in d.<br>
Assign 100 to the corresponding value(s) in f for d_max in d.<br>
In the end, f should have only the following values: 0, 25, 50, 75, and 100.<br>
Note: you don't have to use Numpy in this question.<br>



f = np.where( d_min < d < d_mean, 25)<br>
f = np.where(d == d_mean, 50)<br>
f = np.where(d == d_min , 0)<br>
f = np.where(d == d_max, 100)<br>
f[d_min < d < d_mean] = 25<br>
all(d_min < d < d_mean, 25)


In [34]:
f[(d_min < d) & ( d < d_mean) ] = 25
f[(d_mean < d) & ( d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min ] = 0
f[d == d_max] = 100

In [37]:
print(f)

[[[ 75.  75.  25.  75.  25.]
  [ 75.  75.  25.  75.  75.]
  [ 25.  75.  25.  75.  75.]]

 [[100.  25.  25.   0.  25.]
  [ 75.  75.  75.  25.  25.]
  [ 75.  25.  75.  75.  75.]]]


In [38]:
print(d)

[[[96. 86. 50. 71. 44.]
  [68. 78. 23. 60. 61.]
  [43. 91. 22. 70. 80.]]

 [[98. 37. 18.  3. 22.]
  [75. 97. 84. 35. 32.]
  [96. 18. 74. 66. 69.]]]



<br>
f = list(f.flatten())<br>
print(f)<br>
for i in f:<br>
        i = int(i)<br>
        if d_min < d < d_mean:<br>
                i = 25<br>
        elif d == d_mean:<br>
                i = 50<br>
        elif d == d_min:<br>
                i = 0<br>
        else:<br>
                i = 100<br>
print(f)<br>



<br>
#17. Print d and f. Do you have your expected f?<br>
For instance, if your d is:<br>
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],<br>
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],<br>
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],<br>
       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],<br>
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],<br>
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])<br>
Your f should be:<br>
array([[[ 75.,  75.,  75.,  25.,  75.],<br>
        [ 75.,  75.,  25.,  25.,  25.],<br>
        [ 75.,  25.,  75.,  75.,  75.]],<br>
       [[ 25.,  25.,  25.,  25., 100.],<br>
        [ 75.,  75.,  75.,  75.,  75.],<br>
        [ 25.,  75.,   0.,  75.,  75.]]])<br>


In [36]:
print(d)
print(f)

[[[96. 86. 50. 71. 44.]
  [68. 78. 23. 60. 61.]
  [43. 91. 22. 70. 80.]]

 [[98. 37. 18.  3. 22.]
  [75. 97. 84. 35. 32.]
  [96. 18. 74. 66. 69.]]]
[[[ 75.  75.  25.  75.  25.]
  [ 75.  75.  25.  75.  75.]
  [ 25.  75.  25.  75.  75.]]

 [[100.  25.  25.   0.  25.]
  [ 75.  75.  75.  25.  25.]
  [ 75.  25.  75.  75.  75.]]]



<br>
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values <br>
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:<br>
array([[[ 'D',  'D',  'D',  'B',  'D'],<br>
        [ 'D',  'D',  'B',  'B',  'B'],<br>
        [ 'D',  'B',  'D',  'D',  'D']],<br>
       [[ 'B',  'B',  'B',  'B',  'E'],<br>
        [ 'D',  'D',  'D',  'D',  'D'],<br>
        [ 'B',  'D',   'A',  'D', 'D']]])<br>
Again, you don't need Numpy in this question.<br>


In [42]:
h = np.empty((2, 3, 5), dtype=str)
print(h)

[[['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]

 [['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]]


In [43]:

h[(d_min < d) & ( d < d_mean) ] = "B"
h[(d_mean < d) & ( d < d_max)] = "D"
h[d == d_mean] = "C"
h[d == d_min ] = "A"
h[d == d_max] = "E"

In [44]:
print(h)

[[['D' 'D' 'B' 'D' 'B']
  ['D' 'D' 'B' 'D' 'D']
  ['B' 'D' 'B' 'D' 'D']]

 [['E' 'B' 'B' 'A' 'B']
  ['D' 'D' 'D' 'B' 'B']
  ['D' 'B' 'D' 'D' 'D']]]
